Transaction page
dongumayagay/km602 pull request #12
Opened 2022-11-09 09:53 UTC by chicky-krukie

2022-11-10 14:36 UTC, dongumayagay requested changes
hindi ko pa approved since may iaask ako sayo regarding sa mga naglagay ka ng w-1/5 at w-4/5 which gets ko bakit pero mas madaming way to improve yun. kase pag ginawa mong responsive magiging issue yan, at need mo pa isimplify yung transaction page, yung modal na new transaction gawin mong isang component, yung kada table row sa each gawin mo ding component

2022-11-11 08:24 UTC, chicky-krukie commented
> hindi ko pa approved since may iaask ako sayo regarding sa mga naglagay ka ng w-1/5 at w-4/5 which gets ko bakit pero mas madaming way to improve yun. kase pag ginawa mong responsive magiging issue yan, at need mo pa isimplify yung transaction page, yung modal na new transaction gawin mong isang component, yung kada table row sa each gawin mo ding component

ay yes, sige sige sabihan na lang kita

2022-11-13 17:17 UTC, dongumayagay approved these changes
Approved ko to for now pero may optimization issues pa like dapat yung realtime listener na onSnapshot is nasa onMount function at yung nirereturn na unsubscribe function ng onSnapshot is tawagin mo sa cleanup ng onMount. pero goods overall pasensya na wala pa din Wi-Fi so hirap mag review 😆

2022-11-13 17:17 UTC, merged

2022-11-14 08:28 UTC, chicky-krukie commented
okay lang HASDHFHAHAHA. pero yung sinasabi mo ba na ilalagay sa onMount ay parang ganito ba
![image](https://user-images.githubusercontent.com/67259222/201611481-8922fe28-2973-4de4-a974-bf60d324275a.png)

2022-11-14 09:45 UTC, dongumayagay commented
yep

2022-11-14 09:46 UTC, dongumayagay commented
para di na sya tangalin na yung realtime listener pag lipat ng page or na tanggal na yang component